export type Snippet = {
  id: string;
  label: string;
  code: string;
};

export const SNIPPETS: Snippet[] = [
  { id: "s01", label: "ts-binary-search", code: `function binarySearch(arr: number[], target: number): number {\n  let lo = 0, hi = arr.length - 1;\n  while (lo <= hi) {\n    const mid = (lo + hi) >> 1;\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) lo = mid + 1; else hi = mid - 1;\n  }\n  return -1;\n}` },
  { id: "s02", label: "ts-quicksort", code: `function quicksort(nums: number[]): number[] {\n  if (nums.length < 2) return nums;\n  const [p, ...rest] = nums;\n  return [...quicksort(rest.filter(n => n < p)), p, ...quicksort(rest.filter(n => n >= p))];\n}` },
  { id: "s03", label: "ts-debounce", code: `function debounce<T extends (...args: unknown[]) => void>(fn: T, ms: number) {\n  let t: ReturnType<typeof setTimeout>;\n  return (...args: Parameters<T>) => { clearTimeout(t); t = setTimeout(() => fn(...args), ms); };\n}` },
  { id: "s04", label: "ts-fetch-json", code: `async function fetchJson<T>(url: string): Promise<T> {\n  const res = await fetch(url);\n  if (!res.ok) throw new Error(res.statusText);\n  return res.json() as Promise<T>;\n}` },
  { id: "s05", label: "ts-deep-clone", code: `function deepClone<T>(value: T): T {\n  return structuredClone(value);\n}` },
  { id: "s06", label: "py-binary-search", code: `def binary_search(arr, target):\n    lo, hi = 0, len(arr) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target: return mid\n        if arr[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return -1` },
  { id: "s07", label: "py-list-comp", code: `squares = [n * n for n in range(10) if n % 2 == 0]` },
  { id: "s08", label: "py-read-lines", code: `with open("data.txt", encoding="utf-8") as f:\n    lines = [line.strip() for line in f]` },
  { id: "s09", label: "js-promise-all", code: `async function loadAll(urls) {\n  return Promise.all(urls.map((u) => fetch(u).then((r) => r.text())));\n}` },
  { id: "s10", label: "js-array-unique", code: `const unique = (items) => [...new Set(items)];` },
  { id: "s11", label: "go-http-handler", code: `func hello(w http.ResponseWriter, r *http.Request) {\n\tfmt.Fprintf(w, "hello")\n}` },
  { id: "s12", label: "go-goroutine", code: `go func() {\n\tch <- work()\n}()` },
  { id: "s13", label: "rust-result-map", code: `fn parse_port(s: &str) -> Result<u16, std::num::ParseIntError> {\n    s.parse::<u16>()\n}` },
  { id: "s14", label: "rust-iterator", code: `let total: i32 = nums.iter().filter(|n| **n > 0).sum();` },
  { id: "s15", label: "sql-select", code: `SELECT id, email FROM users WHERE active = TRUE ORDER BY created_at DESC LIMIT 20;` },
  { id: "s16", label: "sql-join", code: `SELECT u.name, o.total FROM users u JOIN orders o ON o.user_id = u.id;` },
  { id: "s17", label: "bash-retry", code: `for i in {1..5}; do curl -fsS "$URL" && break || sleep 1; done` },
  { id: "s18", label: "bash-find-large", code: `find . -type f -size +10M -print` },
  { id: "s19", label: "css-flex-center", code: `.center { display: flex; align-items: center; justify-content: center; }` },
  { id: "s20", label: "html-input", code: `<input type="email" name="email" required autocomplete="email" />` },
  { id: "s21", label: "ts-react-state", code: `const [count, setCount] = useState(0);` },
  { id: "s22", label: "ts-react-effect", code: `useEffect(() => {\n  const id = setInterval(tick, 1000);\n  return () => clearInterval(id);\n}, [tick]);` },
  { id: "s23", label: "ts-zod-parse", code: `const User = z.object({ id: z.string(), age: z.number().int().positive() });\nconst user = User.parse(input);` },
  { id: "s24", label: "ts-express-route", code: `app.get("/health", (_req, res) => res.json({ ok: true }));` },
  { id: "s25", label: "ts-cosine", code: `function cosine(a: number[], b: number[]): number {\n  let dot = 0, na = 0, nb = 0;\n  for (let i = 0; i < a.length; i++) { dot += a[i]*b[i]; na += a[i]*a[i]; nb += b[i]*b[i]; }\n  return dot / (Math.sqrt(na) * Math.sqrt(nb));\n}` },
  { id: "s26", label: "py-requests", code: `resp = requests.get(url, timeout=10)\nresp.raise_for_status()\ndata = resp.json()` },
  { id: "s27", label: "py-dataclass", code: `@dataclass\nclass Point:\n    x: float\n    y: float` },
  { id: "s28", label: "js-regex-email", code: `const EMAIL = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;` },
  { id: "s29", label: "js-flatten", code: `const flatten = (arr) => arr.flatMap((x) => Array.isArray(x) ? flatten(x) : [x]);` },
  { id: "s30", label: "java-stream", code: `List<String> names = users.stream().map(User::name).filter(n -> !n.isBlank()).toList();` },
  { id: "s31", label: "kotlin-null-safe", code: `val city = user?.address?.city ?: "unknown"` },
  { id: "s32", label: "csharp-linq", code: `var active = users.Where(u => u.Active).Select(u => u.Email).ToList();` },
  { id: "s33", label: "php-array-filter", code: `$adults = array_filter($users, fn($u) => $u['age'] >= 18);` },
  { id: "s34", label: "ruby-map", code: `names = users.map { |u| u[:name].downcase }` },
  { id: "s35", label: "swift-filter", code: `let positives = nums.filter { $0 > 0 }` },
  { id: "s36", label: "ts-palindrome", code: `const isPalindrome = (s: string) => s === [...s].reverse().join("");` },
  { id: "s37", label: "ts-two-sum", code: `function twoSum(nums: number[], target: number) {\n  const seen = new Map<number, number>();\n  for (let i = 0; i < nums.length; i++) {\n    const need = target - nums[i];\n    if (seen.has(need)) return [seen.get(need), i];\n    seen.set(nums[i], i);\n  }\n}` },
  { id: "s38", label: "py-fibonacci", code: `def fib(n):\n    a, b = 0, 1\n    for _ in range(n): a, b = b, a + b\n    return a` },
  { id: "s39", label: "py-json-load", code: `import json\npayload = json.loads(text)` },
  { id: "s40", label: "js-timeout-retry", code: `const sleep = (ms) => new Promise((r) => setTimeout(r, ms));` },
  { id: "s41", label: "dockerfile-node", code: `FROM node:22-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nCMD ["npm","start"]` },
  { id: "s42", label: "yaml-github-action", code: `jobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm test` },
  { id: "s43", label: "json-config", code: `{\n  "name": "demo",\n  "scripts": { "test": "vitest" }\n}` },
  { id: "s44", label: "graphql-query", code: `query User($id: ID!) {\n  user(id: $id) { id name posts { title } }\n}` },
  { id: "s45", label: "regex-ipv4", code: `const IPV4 = /^(\\d{1,3}\\.){3}\\d{1,3}$/;` },
  { id: "s46", label: "ts-heapify", code: `function heapify(arr: number[], n: number, i: number) {\n  let largest = i;\n  const l = 2*i+1, r = 2*i+2;\n  if (l < n && arr[l] > arr[largest]) largest = l;\n  if (r < n && arr[r] > arr[largest]) largest = r;\n  if (largest !== i) { [arr[i], arr[largest]] = [arr[largest], arr[i]]; heapify(arr, n, largest); }\n}` },
  { id: "s47", label: "ts-uuid-check", code: `const isUuid = (s: string) => /^[0-9a-f-]{36}$/i.test(s);` },
  { id: "s48", label: "py-merge-dicts", code: `merged = {**defaults, **overrides}` },
  { id: "s49", label: "js-curry-add", code: `const add = (a) => (b) => a + b;` },
  { id: "s50", label: "ts-token-count", code: `const countTokens = async (text: string) => client.messages.countTokens({ model, messages: [{ role: "user", content: text }] });` },
];
